// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAn_RZw1aFCsI6ANINbQw8K7ydZ_e5E2UE',
    appId: '1:787030435485:web:1288d48b5eb9c3ef939674',
    messagingSenderId: '787030435485',
    projectId: 'audiobook-714a1',
    authDomain: 'audiobook-714a1.firebaseapp.com',
    storageBucket: 'audiobook-714a1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiR3W6GZNUj2j4XO6TWeybvFq6MiwIUHE',
    appId: '1:787030435485:android:c4d102a77b55f4e5939674',
    messagingSenderId: '787030435485',
    projectId: 'audiobook-714a1',
    storageBucket: 'audiobook-714a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKKmkYdXAMqOecxmCFoLrl1hFAiCsjEo0',
    appId: '1:787030435485:ios:b8d8a006e63a25b9939674',
    messagingSenderId: '787030435485',
    projectId: 'audiobook-714a1',
    storageBucket: 'audiobook-714a1.firebasestorage.app',
    iosBundleId: 'com.example.audioBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKKmkYdXAMqOecxmCFoLrl1hFAiCsjEo0',
    appId: '1:787030435485:ios:b8d8a006e63a25b9939674',
    messagingSenderId: '787030435485',
    projectId: 'audiobook-714a1',
    storageBucket: 'audiobook-714a1.firebasestorage.app',
    iosBundleId: 'com.example.audioBook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAn_RZw1aFCsI6ANINbQw8K7ydZ_e5E2UE',
    appId: '1:787030435485:web:6e4b4870070f527f939674',
    messagingSenderId: '787030435485',
    projectId: 'audiobook-714a1',
    authDomain: 'audiobook-714a1.firebaseapp.com',
    storageBucket: 'audiobook-714a1.firebasestorage.app',
  );
}
