// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:audio_book/data/models/book_model.dart';
import 'package:audio_book/data/models/chapter_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(BookModelAdapter());
    registerAdapter(ChapterModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(BookModelAdapter());
    registerAdapter(ChapterModelAdapter());
  }
}
